OrdererOrgs:
  - Name: Orderer
    Domain: lgy
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
#      - Hostname: orderer4
#      - Hostname: orderer5
PeerOrgs:
  - Name: Org1
    Domain: lgy.svc.cluster.local
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
#  - Name: Org2
#    Domain: org2.lgy.com
#    EnableNodeOUs: true
#    Template:
#      Count: 2
#    Users:
#      Count: 1
